# 📘 Ejercicios de Arrays y Matrices con NumPy
---Este notebook contiene ejercicios prácticos para trabajar con **arrays y matrices en NumPy**.
Completa cada celda de código con la solución correspondiente.

**Ejercicio 1:** Crear un array de 10 elementos con ceros.

# Sección nueva

In [ ]:
import numpy as np



**Ejercicio 2:** Genera un array con los números del 1 al 20.

In [ ]:
# Tu código aquí
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

**Ejercicio 3:** Crea un array con los números pares del 2 al 50.

In [ ]:
# Tu código aquí
np.arange(2, 51, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

**Ejercicio 4:** Genera un array de tamaño 8 donde todos los valores sean 7.

In [ ]:
# Tu código aquí
np.full(8, 7)

array([7, 7, 7, 7, 7, 7, 7, 7])

**Ejercicio 5:** Crea una matriz de 4x4 con valores aleatorios entre 0 y 1.

In [ ]:
# Tu código aquí
np.random.rand(4, 4)

array([[0.83249619, 0.93748697, 0.7829274 , 0.74377672],
       [0.9292048 , 0.4072976 , 0.03962389, 0.66583835],
       [0.80203224, 0.86588249, 0.81432864, 0.75686557],
       [0.36485026, 0.37879344, 0.43396382, 0.23933343]])

**Ejercicio 6:** Realiza la suma elemento a elemento de los arrays a=[1,2,3], b=[4,5,6].

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
# Tu código aquí
a + b

array([5, 7, 9])

**Ejercicio 7:** Multiplica dos matrices 3x3 de enteros aleatorios entre 1 y 10.

In [ ]:
# Tu código aquí
a = np.random.randint(1, 11, size=(3, 3))
b = np.random.randint(1, 11, size=(3, 3))
new_arr = np.dot(a, b) # linea eficiente a @ b
print("\nResultado de multiplicar dos matrices 3x3:\n", new_arr)


Resultado de multiplicar dos matrices 3x3:
 [[155  96  90]
 [ 83  78  41]
 [149  86  74]]


**Ejercicio 8:** Crea un array de 15 valores aleatorios entre 1 y 100 e imprime su máximo, mínimo y promedio.

In [ ]:
# Tu código aquí
array = np.random.randint(1, 101, size=15)
print("Array: ", array)
print("Máximo:", array.max())
print("Mínimo:", array.min())
print("Promediio:", array.mean())

Array:  [39 75 19 35 63 50 37 77 45 17 72 72 63 57 70]
Máximo: 77
Mínimo: 17
Promediio: 52.733333333333334


**Ejercicio 9:** Genera una matriz 5x5 con valores del 1 al 25 y extrae su diagonal.

In [ ]:
# Tu código aquí
matriz = np.arange(1, 26).reshape(5, 5)
diagonal = np.diag(matriz)
print("\nMatriz:\n", matriz)
print("\nDiagonal:\n", diagonal)


Matriz:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Diagonal:
 [ 1  7 13 19 25]


**Ejercicio 10
:** Dada una matriz 5x5 de enteros aleatorios entre 1 y 20, calcula la suma de cada fila y columna.

In [ ]:
# Tu código aquí
matriz = np.random.randint(1, 21, size=(5, 5))

sum_filas = matriz.sum(axis=1) #sumo horizontalmente
sum_columnas = matriz.sum(axis=0) #sumo verticalmente

print("Matriz:\n", matriz)
print("Suma de filas: ", sum_filas)
print("Suma de columnas: ", sum_columnas)

Matriz:
 [[10  3 13 20 15]
 [ 2 19 11 18  8]
 [ 8  9 12  3  7]
 [ 7  9  9 16  9]
 [ 6  7  4 14  8]]
Suma de filas:  [61 58 39 50 39]
Suma de columnas:  [33 47 49 71 47]
